### ISSUE TITLE
Upload an Audio File Instead of Recording via Microphone

### ISSUE THREAD

**Issue by mbrksntrk** [gryhkn/voice-cloning#2]
I'd like to request a feature that allows users to upload audio files instead of just recording through the microphone. This would enable users to utilize pre-recorded audio content, accommodating a wider range of use cases. Support for common audio formats like .mp3 and .wav, along with upload progress feedback, would significantly enhance the application's flexibility and user experience.

**Comment by gryhkn** [comment]
Great feature, let's do it.

**Comment by gryhkn** [comment]
Done, I've added upload feature with recording.
